#!/bin/sh -ex
# build the main.js from the Main elm module
cd "`git rev-parse --show-toplevel`"

ver=0.19.1
elm=`command -v elm || echo elm-stuff/$ver/elm`
if ! test -x "$elm"
  then
    mkdir -p elm-stuff/$ver
    curl -L https://github.com/elm/compiler/releases/download/$ver/binary-for-linux-64-bit.gz | gunzip >elm-stuff/$ver/elm
    chmod +x elm-stuff/$ver/elm
fi

"$elm" make Main.elm ${1---optimize} --output=main.js
